version: '3.8'

services:
  SqlServerDb:
      container_name: SqlServerContainer
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
          - 8002:1433
      environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Sepehr2023@ 
  sepehrapi:
      container_name: SepehrWebApi
      image: ${DOCKER_REGISTRY-}webapisqlserverdockerdemo
      environment:
        - ASPNETCORE_ENVIRONMENT=Development 
        - ASPNETCORE_HTTP_PORTS=8000
        - ASPNETCORE_URLS = http://localhost:8000
      ports:
        - "8000:8080" #map 8080 port to 8000 local port
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
          - SqlServerDb

  # sepehr-api:
  #   container_name: sepehrapi
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   restart: on-failure
  #   depends_on:
  #     - sepehrapi-db
